<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * The 'services' table represents the catalogue of offerings listed by
     * sellers. A seller can have many services.
     *
     * Pricing model:
     *   - 'rate'          → the seller's hourly/daily rate (or base unit price)
     *   - 'dynamic_price' → the ACTUAL price for a given request, computed at
     *                       order time (by scope, complexity, add-ons, etc.)
     *                       This column on the SERVICE acts as the default
     *                       starting price before negotiation.
     *
     * AI Hook: 'ai_description_score' (float) can hold a readability /
     * quality score generated by an LLM to prompt sellers to improve weak
     * listings, directly increasing conversion.
     *
     * AI Hook: 'category_id' (FK) can be predicted automatically by an NLP
     * classifier from the title + description when a seller creates a service.
     *
     * AI Hook: 'search_embedding' (vector/json) enables semantic search
     * ("find me a logo designer who understands fintech") powered by a
     * vector similarity query instead of keyword matching.
     */
    public function up(): void
    {
        // Optional: service categories (normalised reference table)
        Schema::create('service_categories', function (Blueprint $table) {
            $table->id();
            $table->string('name', 100)->unique();
            $table->string('slug', 100)->unique();
            $table->string('icon', 100)->nullable(); // e.g. heroicon or emoji
            $table->timestamps();
        });

        Schema::create('services', function (Blueprint $table) {
            $table->id();

            // The seller who owns this listing
            $table->foreignId('seller_id')
                ->constrained('sellers')
                ->cascadeOnDelete();

            // Optional category grouping
            $table->foreignId('category_id')
                ->nullable()
                ->constrained('service_categories')
                ->nullOnDelete();

            $table->string('title', 255);
            $table->text('description');

            // Seller's base hourly/unit rate (e.g. $50/hr)
            $table->decimal('rate', 10, 2);

            // Default price presented to the client before customisation.
            // On a real request, this flows into 'requests.final_price'
            // after any AI-driven or manual negotiation.
            $table->decimal('dynamic_price', 10, 2);

            // Delivery time in calendar days
            $table->unsignedSmallInteger('delivery_days')->default(1);

            // Number of revisions included
            $table->unsignedSmallInteger('revisions_included')->default(1);

            // Soft status toggle (admin can suspend a service without deleting)
            $table->enum('status', ['active', 'paused', 'suspended'])->default('active');

            // Cover image for the service card
            $table->string('thumbnail_path')->nullable();

            // JSON array of additional image paths for the gallery
            $table->json('gallery_paths')->nullable();

            // Cached aggregates for fast display (updated via observer/event)
            $table->decimal('average_rating', 3, 2)->default(0.00);
            $table->unsignedInteger('total_orders')->default(0);

            // --- AI HOOK PLACEHOLDERS (commented out, ready to enable) ---
            // $table->json('search_embedding')->nullable();
            // $table->float('ai_description_score')->nullable();   // 0.0 – 1.0
            // $table->json('auto_suggested_tags')->nullable();

            $table->timestamps();
            $table->softDeletes();

            // Full-text search index (MySQL/PostgreSQL)
            $table->fullText(['title', 'description']);
            $table->index('status');
            $table->index('dynamic_price');
            $table->index('average_rating');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('services');
        Schema::dropIfExists('service_categories');
    }
};
