<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * The 'requests' table is the CORE transaction entity of the platform.
     * It links a client to a seller's service and tracks the full lifecycle
     * from placement to completion.
     *
     * Status lifecycle:
     *   pending → in_progress → delivered → completed
     *                        ↘ disputed (via disputes table, not a status here)
     *                        ↘ cancelled
     *
     * Financial flow:
     *   1. Client places request  → 'final_price' deducted from client wallet_balance
     *                               (held in escrow, tracked via 'escrow_amount')
     *   2. Seller delivers        → status becomes 'delivered'
     *   3. Client approves        → status becomes 'completed',
     *                               escrow_amount credited to seller wallet_balance
     *
     * AI Hook: 'scope_summary' (text) can be auto-generated by an LLM
     * summarising 'order_details' for the seller's dashboard digest.
     *
     * AI Hook: 'sentiment_score' (float) on the rating can be derived from
     * an NLP analysis of 'review_text', giving admins richer signal than
     * a 1-5 star rating alone.
     *
     * AI Hook: 'ai_price_suggestion' (decimal) can be pre-populated when
     * a client submits a request, showing them a fair-market estimate before
     * they confirm the final_price.
     */
    public function up(): void
    {
        Schema::create('requests', function (Blueprint $table) {
            $table->id();

            // ── Parties ──────────────────────────────────────────────────
            $table->foreignId('client_id')
                ->constrained('clients')
                ->restrictOnDelete(); // Preserve order history even if client soft-deleted

            $table->foreignId('seller_id')
                ->constrained('sellers')
                ->restrictOnDelete();

            $table->foreignId('service_id')
                ->constrained('services')
                ->restrictOnDelete();

            // ── Status ───────────────────────────────────────────────────
            $table->enum('status', [
                'pending',      // Placed, awaiting seller acceptance
                'in_progress',  // Seller accepted and is working
                'delivered',    // Seller marked as delivered, awaiting client review
                'completed',    // Client approved, funds released to seller
                'cancelled',    // Cancelled before work began (full refund)
                'refunded',     // Post-dispute refund issued
            ])->default('pending');

            // ── Financials ───────────────────────────────────────────────
            // Price agreed at order time (may differ from service.dynamic_price
            // after negotiation or custom scope).
            $table->decimal('final_price', 10, 2);

            // Amount currently held in escrow (decrements to 0 on completion/refund)
            $table->decimal('escrow_amount', 10, 2)->default(0.00);

            // Platform commission taken on completion (e.g. 10%)
            $table->decimal('platform_fee', 10, 2)->default(0.00);

            // ── Order Details ────────────────────────────────────────────
            // Freeform JSON capturing the client's specific requirements,
            // attachments list, deadline preferences, etc.
            $table->json('order_details')->nullable();

            // Delivery deadline agreed at order time
            $table->timestamp('deadline_at')->nullable();

            // Timestamp when seller actually delivered
            $table->timestamp('delivered_at')->nullable();

            // Timestamp when client approved / request completed
            $table->timestamp('completed_at')->nullable();

            // ── Rating & Review ──────────────────────────────────────────
            // Rating is nullable; only populated after status = 'completed'
            $table->unsignedTinyInteger('rating')->nullable(); // 1 – 5

            // Optional written review from the client
            $table->text('review_text')->nullable();

            // Timestamp when review was submitted
            $table->timestamp('reviewed_at')->nullable();

            // ── AI HOOK PLACEHOLDERS (commented out, ready to enable) ────
            // $table->text('scope_summary')->nullable();          // LLM-generated brief
            // $table->float('sentiment_score')->nullable();       // -1.0 to 1.0
            // $table->decimal('ai_price_suggestion', 10, 2)->nullable();

            $table->timestamps();
            $table->softDeletes();

            // ── Indexes ──────────────────────────────────────────────────
            $table->index('status');
            $table->index('deadline_at');
            $table->index(['client_id', 'status']);
            $table->index(['seller_id', 'status']);
            $table->index('rating');

            // Ensure rating is always in range (DB-level constraint)
            // Note: Add CHECK constraint via raw statement in a separate migration
            // if your DB supports it (MySQL 8+, PostgreSQL, SQLite 3.25+).
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('requests');
    }
};
